### PR TITLE
Fix: changing sync annotation=false should delete

### LINKED ISSUE #76: Disabling or removing 'consul.hashicorp.com/service-sync' annotation does nothing
### What i'm trying to do
* Consul-k8s is running with `-k8s-default-sync=false`
* Starting with a synced service :
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-meta-OWNER: foobar
    consul.hashicorp.com/service-name: my-kubernetes-hosted-svc
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-tags: foo,bar
[...]
```

### What is the problem
When we set `consul.hashicorp.com/service-sync` to `"false"` or if we remove it (using kubectl edit) :
* Consul-k8s does nothing
* Service is still synchronized

### What it should be doing (IMO)
* Removing all registered instances for this service when we remove (or disable) this annotation

The only way I find to do so is to delete this service and create it again without this annotation.

Did I missed something or is it the intended behavior ?
Thx a lot :) !

### PR DESCRIPTION
**Pull request by lkysow**
Previously, if consul.hashicorp.com/service-sync was set to true and
then set to false, the service wouldn't get deleted.

Fixes #76

### CODE REVIEW

File: catalog/from-k8s/resource.go [hunk 1]
```diff
@@ -151,18 +164,23 @@ func (t *ServiceResource) Upsert(key string, raw interface{}) error {
 func (t *ServiceResource) Delete(key string) error {
 	t.serviceLock.Lock()
 	defer t.serviceLock.Unlock()
+	t.doDelete(key)
+	t.Log.Info("delete", "key", key)
+	return nil
+}
```
Comment (ishustava) [inline catalog/from-k8s/resource.go]: This function never returns an actual error.

Comment (lkysow) [reply catalog/from-k8s/resource.go]: Yes but it's implementing the `controller.Resource` interface:
https://github.com/hashicorp/consul-k8s/blob/81026eb1a4cb2c7c3c75b03ff36eb8328a0300e1/helper/controller/resource.go#L12-L27

Comment (ishustava) [reply catalog/from-k8s/resource.go]: got it!
