### PR TITLE
connect: endpoints controller deletes ACL token when service is deregistered

### LINKED ISSUE #540: Kubernetes PreStop hook failing to deregister ACLs and service instances
#### Overview of the Issue

Consul Connect Inject created ACLs not being deleted after a Kubernetes pods is deleted.  It seems that the issue is that the `envoy-sidecar` `preStop` hook is failing.  As far as I can tell neither the `consul services deregister` or `consul logout` are executed.

The service instance in Consul is eventually gets deleted.  The `consul-connect-injector-webhook` pod identifies the missing pod and deletes it, but the ACL remains.

Looking at the Kubernetes events with `kubectl get events --all-namespaces -w` shows:

```
pedher-server-delete   0s          Warning   FailedPreStopHook   pod/static-server-7ffbbfb96f-jr7jf    Exec lifecycle hook ([/bin/sh -ec /consul/connect-inject/consul services deregister \
  -token-file="/consul/connect-inject/acl-token" \
  /consul/connect-inject/service.hcl
/consul/connect-inject/consul logout \
  -token-file="/consul/connect-inject/acl-token"]) for Container "envoy-sidecar" in Pod "static-server-7ffbbfb96f-jr7jf_pedher-server-delete(adf7afbf-7358-498f-88c1-c875351f010e)" failed - error: command '/bin/sh -ec /consul/connect-inject/consul services deregister \
  -token-file="/consul/connect-inject/acl-token" \
  /consul/connect-inject/service.hcl
/consul/connect-inject/consul logout \
  -token-file="/consul/connect-inject/acl-token"' exited with 1: Error registering service "static-server": Put "https://10.31.236.67:8501/v1/agent/service/deregister/static-server-7ffbbfb96f-jr7jf-static-server": dial tcp 10.31.236.67:8501: i/o timeout
, message: "Error registering service \"static-server\": Put \"https://10.31.236.67:8501/v1/agent/service/deregister/static-server-7ffbbfb96f-jr7jf-static-server\": dial tcp 10.31.236.67:8501: i/o timeout\n"
```

This is a bit of a side note...   If `terminationGracePeriodSeconds` is not long enough on the pod you get a `137` exit code.

<details>
  <summary>K8s event error if terminationGracePeriodSeconds not set</summary>

```
pedher-server-delete   0s          Warning   FailedPreStopHook   pod/static-server-855444b4d7-c5bgp    Exec lifecycle hook ([/bin/sh -ec /consul/connect-inject/consul services deregister \
  -token-file="/consul/connect-inject/acl-token" \
  /consul/connect-inject/service.hcl
/consul/connect-inject/consul logout \
  -token-file="/consul/connect-inject/acl-token"]) for Container "envoy-sidecar" in Pod "static-server-855444b4d7-c5bgp_pedher-server-delete(7d0cda43-8dc3-43b6-8da8-8f04f7a8a4b7)" failed - error: command '/bin/sh -ec /consul/connect-inject/consul services deregister
 \
  -token-file="/consul/connect-inject/acl-token" \
  /consul/connect-inject/service.hcl
/consul/connect-inject/consul logout \
  -token-file="/consul/connect-inject/acl-token"' exited with 137: , message: ""
```

</details>

Execing into the `envoy-sidecar` container and running the `preStop` commands manually seems to work just fine, both the service instance and the ACL are deleted, though you start getting a bunch of other errors about `agent.client: RPC failed to server: method=Catalog.Deregister server=10.31.236.71:8300 error="rpc error making call: ACL not found"` which I won't get to here.

```bash
$ kubectl exec -ti static-server-855444b4d7-fdnsj -c envoy-sidecar -- /consul/connect-inject/consul services deregister -token-file="/consul/connect-inject/acl-token" /consul/connect-inject/service.hcl
Deregistered service: static-server-855444b4d7-fdnsj-static-server
Deregistered service: static-server-855444b4d7-fdnsj-static-server-sidecar-proxy

$ kubectl exec -ti static-server-855444b4d7-fdnsj -c envoy-sidecar -- /consul/connect-inject/consul logout -token-file="/consul/connect-inject/acl-token"
```

The `preStop` hook in question is:

```yaml
    name: envoy-sidecar
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -ec
          - |-
            /consul/connect-inject/consul services deregister \
              -token-file="/consul/connect-inject/acl-token" \
              /consul/connect-inject/service.hcl
            /consul/connect-inject/consul logout \
              -token-file="/consul/connect-inject/acl-token"
```

#### Reproduction Steps

I created a test cluster based off of the [Secure Consul and Registered Services on Kubernetes](https://learn.hashicorp.com/tutorials/consul/kubernetes-secure-agents?in=consul/kubernetes#upgrade-to-a-secured-consul-service-mesh) tutorial and reproduced it there in order to keep things as simple as possible.

Steps to reproduce this issue, eg:

1. Create your gossip key `kubectl create secret generic consul-gossip-encryption-key --from-literal=key=$(consul keygen)`.
2. Create a cluster via Helm with `helm install -f helm-consul-h0-values.yaml demo-0 hashicorp/consul --wait`:
   ```yaml
   ---
   global:
     name: consul
     image: hashicorp/consul:1.9.6
     domain: consul.i.avinode.com
     datacenter: demo-h0
   
     tls:
       enabled: true
       enableAutoEncrypt: true
       verify: true
   
     gossipEncryption:
       secretName: consul-gossip-encryption-key
       secretKey: key
   
     acls:
       manageSystemACLs: true
       # createReplicationToken: true
   
   ui:
     service:
       annotations: |
         service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
       type: LoadBalancer
       additionalSpec: |
         loadBalancerIP: 10.31.237.250
   
   connectInject:
     enabled: true
   controller:
     enabled: true
   ...

   ```

1. Create the namespace: `kubectl create namespace pedher-server-delete`
2. Deploy the test service with `kubectl --namespace=pedher-server-delete apply -f static-server.yaml`:
   ```yaml
   ---
   apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: static-server
     namespace: pedher-server-delete
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: static-server
     namespace: pedher-server-delete
   spec:
     selector:
       app: static-server
     ports:
       - port: 1234
         targetPort: 8080
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     labels:
       app: static-server
     name: static-server
     namespace: pedher-server-delete
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: static-server
     template:
       metadata:
         namespace: pedher-server-delete
         annotations:
           consul.hashicorp.com/connect-inject: 'true'
         labels:
           app: static-server
       spec:
         terminationGracePeriodSeconds: 120
         containers:
           - name: static-server
             image: hashicorp/http-echo:latest
             args:
               - -text="hello world"
               - -listen=:8080
             ports:
               - containerPort: 8080
                 name: http
         serviceAccountName: static-server
   ...

   ```

1. Watch the events on the K8s cluster in a separate terminal: `kubectl get events --all-namespaces -w`
2. Delete the pod with `kubectl --namespace=pedher-server-delete delete pods -l 'app=static-server'` and wait for the error to pop up in the K8s events.  Might take a minute.

### Consul info for both Client and Server

This output is suspect...

<details>
  <summary>Client info</summary>

```
$ kubectl exec -ti static-server-855444b4d7-fdnsj -c envoy-sidecar -- /consul/connect-inject/consul info  -token-file="/consul/connect-inject/acl-token"
Error querying agent: Unexpected response code: 403 (Permission denied)
command terminated with exit code 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = bbcbb733
	version = 1.9.6
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.31.236.71:8300
	server = true
raft:
	applied_index = 9991
	commit_index = 9991
	fsm_pending = 0
	last_contact = 1.973439ms
	last_log_index = 9991
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:cae1293d-2e1a-5f15-a3a4-f34240d9e86d Address:10.31.236.18:8300} {Suffrage:Voter ID:5afe13d6-adf4-9b02-a11e-28d96581f5f8 Address:10.31.236.59:8300} {Suffrage:Voter ID:ec88fd17-b382-36c8-b135-c1fd28a06f24 Address:10.31.236.71:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 110
	max_procs = 2
	os = linux
	version = go1.15.12
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6
	members = 6
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Running on Azure AKS.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"6b3f9b283463c1d5a2455df301182805e65c7145", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:47Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ helm --namespace=pedher-consul-server-1 list
NAME    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART           APP VERSION
demo-0  pedher-consul-server-1  1               2021-06-17 16:34:10.162353 +0200 CEST   deployed        consul-0.31.1   1.9.4

$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

### Log Fragments

Connect injector logs via `kubectl  logs -l 'app=consul,component=connect-injector' -f`:

```
2021-06-18T08:31:31.960Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=10s
2021-06-18T08:33:44.389Z [INFO]  cleanupResource: found service instance from terminated pod still registered: pod=static-server-7ffbbfb96f-pvkjk id=static-server-7ffbbfb96f-pvkjk-static-server ns=
2021-06-18T08:33:44.414Z [INFO]  cleanupResource: service instance deregistered: id=static-server-7ffbbfb96f-pvkjk-static-server ns=
2021-06-18T08:33:44.416Z [INFO]  cleanupResource: found service instance from terminated pod still registered: pod=static-server-7ffbbfb96f-pvkjk id=static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy ns=
2021-06-18T08:33:44.455Z [INFO]  cleanupResource: service instance deregistered: id=static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy ns=
```

Consul server logs via `kubectl  logs -l 'app=consul,component=server' -f`:  **Nothing in the logs**

Consul client logs via `kubectl  logs -l 'app=consul,component=client' -f`:

```
2021-06-18T08:31:36.420Z [INFO]  agent: Synced service: service=static-server-7ffbbfb96f-6zxhz-static-server
2021-06-18T08:31:36.589Z [INFO]  agent: Synced service: service=static-server-7ffbbfb96f-6zxhz-static-server-sidecar-proxy
2021-06-18T08:31:42.611Z [INFO]  agent: Synced check: check=service:static-server-7ffbbfb96f-6zxhz-static-server-sidecar-proxy:2
2021-06-18T08:31:42.634Z [INFO]  agent: Synced check: check=pedher-server-delete/static-server-7ffbbfb96f-6zxhz-static-server/kubernetes-health-check
2021-06-18T08:31:42.648Z [INFO]  agent: Synced check: check=pedher-server-delete/static-server-7ffbbfb96f-6zxhz-static-server/kubernetes-health-check
2021-06-18T08:31:42.665Z [INFO]  agent: Synced check: check=service:static-server-7ffbbfb96f-6zxhz-static-server-sidecar-proxy:2
2021-06-18T08:31:43.722Z [INFO]  agent: Synced check: check=pedher-server-delete/static-server-7ffbbfb96f-6zxhz-static-server/kubernetes-health-check
2021-06-18T08:31:43.738Z [INFO]  agent: Synced check: check=service:static-server-7ffbbfb96f-6zxhz-static-server-sidecar-proxy:2
2021-06-18T08:31:45.075Z [INFO]  agent: Synced check: check=service:static-server-7ffbbfb96f-6zxhz-static-server-sidecar-proxy:1
2021-06-18T08:31:47.463Z [WARN]  agent: Check socket connection failed: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1 error="dial tcp 10.31.236.77:20000: i/o timeout"
2021-06-18T08:31:47.463Z [WARN]  agent: Check is now critical: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1
2021-06-18T08:31:47.480Z [INFO]  agent: Synced check: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1
2021-06-18T08:32:07.464Z [WARN]  agent: Check socket connection failed: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1 error="dial tcp 10.31.236.77:20000: i/o timeout"
2021-06-18T08:32:07.464Z [WARN]  agent: Check is now critical: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1
2021-06-18T08:32:27.464Z [WARN]  agent: Check socket connection failed: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1 error="dial tcp 10.31.236.77:20000: i/o timeout"
2021-06-18T08:32:27.464Z [WARN]  agent: Check is now critical: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1
2021-06-18T08:32:47.465Z [WARN]  agent: Check socket connection failed: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1 error="dial tcp 10.31.236.77:20000: i/o timeout"
2021-06-18T08:32:47.465Z [WARN]  agent: Check is now critical: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1
2021-06-18T08:33:07.465Z [WARN]  agent: Check socket connection failed: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1 error="dial tcp 10.31.236.77:20000: i/o timeout"
2021-06-18T08:33:07.465Z [WARN]  agent: Check is now critical: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1
2021-06-18T08:33:27.465Z [WARN]  agent: Check socket connection failed: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1 error="dial tcp 10.31.236.77:20000: i/o timeout"
2021-06-18T08:33:27.466Z [WARN]  agent: Check is now critical: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1
2021-06-18T08:33:44.413Z [INFO]  agent: Deregistered service: service=static-server-7ffbbfb96f-pvkjk-static-server
2021-06-18T08:33:44.413Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=service-http-checks error="Internal cache failure: service 'static-server-7ffbbfb96f-pvkjk-static-server' not in agent state" index=1
2021-06-18T08:33:44.442Z [INFO]  agent: Synced check: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:2
2021-06-18T08:33:44.442Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=service-http-checks error="Internal cache failure: service 'static-server-7ffbbfb96f-pvkjk-static-server' not in agent state" index=1
2021-06-18T08:33:44.442Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=service-http-checks error="Internal cache failure: service 'static-server-7ffbbfb96f-pvkjk-static-server' not in agent state" index=1
2021-06-18T08:33:44.443Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=service-http-checks error="Internal cache failure: service 'static-server-7ffbbfb96f-pvkjk-static-server' not in agent state" index=1
2021-06-18T08:33:44.454Z [INFO]  agent: Deregistered service: service=static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy
2021-06-18T08:33:47.466Z [WARN]  agent: Check socket connection failed: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1 error="dial tcp 10.31.236.77:20000: i/o timeout"
2021-06-18T08:33:47.466Z [WARN]  agent: Check is now critical: check=service:static-server-7ffbbfb96f-pvkjk-static-server-sidecar-proxy:1

```

Kubernetes events `kubectl get events --all-namespaces -w`:

```
pedher-server-delete     0s          Warning   FailedPreStopHook        pod/static-server-7ffbbfb96f-pvkjk                                  Exec lifecycle hook ([/bin/sh -ec /consul/connect-inject/consul services deregister \
  -token-file="/consul/connect-inject/acl-token" \
  /consul/connect-inject/service.hcl
/consul/connect-inject/consul logout \
  -token-file="/consul/connect-inject/acl-token"]) for Container "envoy-sidecar" in Pod "static-server-7ffbbfb96f-pvkjk_pedher-server-delete(62d042c9-6171-4f0c-8d91-2a9e6534c2df)" failed - error: command '/bin/sh -ec /consul/connect-inject/consul services deregister \
  -token-file="/consul/connect-inject/acl-token" \
  /consul/connect-inject/service.hcl
/consul/connect-inject/consul logout \
  -token-file="/consul/connect-inject/acl-token"' exited with 1: Error registering service "static-server": Put "https://10.31.236.67:8501/v1/agent/service/deregister/static-server-7ffbbfb96f-pvkjk-static-server": dial tcp 10.31.236.67:8501: i/o timeout
, message: "Error registering service \"static-server\": Put \"https://10.31.236.67:8501/v1/agent/service/deregister/static-server-7ffbbfb96f-pvkjk-static-server\": dial tcp 10.31.236.67:8501: i/o timeout\n"
```

### PR DESCRIPTION
**Pull request by ishustava**
Fixes #540 

Changes proposed in this PR:
- Modify endpoints controller to delete ACL tokens for each service instance that it deregisters
- Remove TLS+ACLs table tests from endpoints controller tests. These tests were testing that endpoints controller works with a client configured to have TLS and ACLs. I thought this test was not necessary because there isn't any code in the controller that behaves differently if the consul client is configured with any of those and as a result there's no way these tests could fail. The tests testing to the new ACL logic are there but they are only testing the logic that was added and configure test agent to accommodate for that.
- Create test package under `helper` and move `GenerateServerCerts` function from `subcommand/common` there because it was used outside of `subcommand`. 
- Create a helper test function to set up auth methods and refactor existing `connect-init` command tests to use that function.
- Minor editing fixes of comments etc.

How I've tested this PR:
* unit tests 
* acceptance tests in hashicorp/consul-helm#1056

How I expect reviewers to test this PR:
- code review

Checklist:
- [x] Tests added
- [x] CHANGELOG entry added (*HashiCorp engineers only, community PRs should not add a changelog entry*)

### CODE REVIEW

File: connect-inject/endpoints_controller_ent_test.go [hunk 1]
```diff
@@ -385,10 +385,10 @@ func TestReconcileUpdateEndpointWithNamespaces(t *testing.T) {
 			consulSvcName              string
 			k8sObjects                 func() []runtime.Object
 			initialConsulSvcs          []*api.AgentServiceRegistration
-			expectedNumSvcInstances    int
```
Comment (ishustava) [inline connect-inject/endpoints_controller_ent_test.go:388]: This was not necessary since we can just do `len(expectedConsulSvcInstances)`

File: connect-inject/endpoints_controller.go [hunk 2]
```diff
@@ -710,19 +716,94 @@ func (r *EndpointsController) deregisterServiceOnAllAgents(ctx context.Context,
...
+	tokenMetaJSON := matches[1]
+
+	var tokenMeta map[string]string
+	err := json.Unmarshal([]byte(tokenMetaJSON), &tokenMeta)
+	if err != nil {
+		return nil, fmt.Errorf("failed to unmarshal token metadata '%s': %s", tokenMetaJSON, err)
+	}
+
+	return tokenMeta, nil
+}
```
Comment (thisisnotashwin) [inline connect-inject/endpoints_controller.go:805]: 🥵 this looks difficult!! great job on making it so readable!

File: connect-inject/endpoints_controller_ent_test.go [hunk 3]
```diff
@@ -1259,9 +1522,30 @@ func TestReconcileDeleteEndpointWithNamespaces(t *testing.T) {
...
+							// When mirroring is enabled, the auth method will be created in the "default" Consul namespace.
+							if ts.Mirror {
+								writeOpts.Namespace = "default"
+							}
+							test.SetupK8sAuthMethodWithNamespaces(t, consulClient, svc.Name, svc.Meta[MetaKeyKubeNS], ts.ExpConsulNS, ts.Mirror, ts.MirrorPrefix)
+							token, _, err = consulClient.ACL().Login(&api.ACLLoginParams{
+								AuthMethod:  test.AuthMethod,
+								BearerToken: test.ServiceAccountJWTToken,
+								Meta: map[string]string{
+									"pod": fmt.Sprintf("%s/%s", svc.Meta[MetaKeyKubeNS], svc.Meta[MetaKeyPodName]),
```
Comment (thisisnotashwin) [inline connect-inject/endpoints_controller_ent_test.go:1542]:
```suggestion
									TokenMetaPodNameKey: fmt.Sprintf("%s/%s", svc.Meta[MetaKeyKubeNS], svc.Meta[MetaKeyPodName]),
```

Comment (thisisnotashwin) [reply connect-inject/endpoints_controller_ent_test.go:1542]: This is the most Ashwin review isnt it

File: connect-inject/endpoints_controller_ent_test.go [hunk 4]
```diff
@@ -983,134 +976,357 @@ func TestReconcileUpdateEndpointWithNamespaces(t *testing.T) {
...
+							// When mirroring is enabled, the auth method will be created in the "default" Consul namespace.
+							if ts.Mirror {
+								writeOpts.Namespace = "default"
+							}
+							test.SetupK8sAuthMethodWithNamespaces(t, consulClient, svc.Name, svc.Meta[MetaKeyKubeNS], ts.ExpConsulNS, ts.Mirror, ts.MirrorPrefix)
+							token, _, err := consulClient.ACL().Login(&api.ACLLoginParams{
+								AuthMethod:  test.AuthMethod,
+								BearerToken: test.ServiceAccountJWTToken,
+								Meta: map[string]string{
+									"pod": fmt.Sprintf("%s/%s", svc.Meta[MetaKeyKubeNS], svc.Meta[MetaKeyPodName]),
```
Comment (thisisnotashwin) [inline connect-inject/endpoints_controller_ent_test.go:1232]:
```suggestion
									TokenMetaPodNameKey: fmt.Sprintf("%s/%s", svc.Meta[MetaKeyKubeNS], svc.Meta[MetaKeyPodName]),
```

File: subcommand/connect-init/command_ent_test.go [hunk 5]
```diff
@@ -25,50 +24,50 @@ func TestRun_ServicePollingWithACLsAndTLSWithNamespaces(t *testing.T) {
 		name                   string
 		tls                    bool
 		consulServiceNamespace string
-		authMethod             string
+		acls                   bool
```
Comment (thisisnotashwin) [inline subcommand/connect-init/command_ent_test.go:27]: This refactor is BRILLIANT

File: helper/test/test_util.go [hunk 6]
```diff
@@ -0,0 +1,187 @@
...
+// SetupK8sAuthMethod create a k8s auth method and a binding rule in Consul for the
+// given k8s service and namespace.
+func SetupK8sAuthMethod(t *testing.T, consulClient *api.Client, serviceName, k8sServiceNS string) {
+	SetupK8sAuthMethodWithNamespaces(t, consulClient, serviceName, k8sServiceNS, "", false, "")
+}
+
+// SetupK8sAuthMethodWithNamespaces creates a k8s auth method and binding rule
+// in Consul for the k8s service name and namespace. It sets up the auth method and the binding
+// rule so that it works with consul namespaces.
+func SetupK8sAuthMethodWithNamespaces(t *testing.T, consulClient *api.Client, serviceName, k8sServiceNS, consulNS string, mirrorNS bool, nsPrefix string) {
```
Comment (thisisnotashwin) [inline helper/test/test_util.go:69]: ❤️

**Review by thisisnotashwin — APPROVED** [review]
It took a while to read but this is an excellent PR!! I'm surprised that we only had to make changes to the endpoints controller in order for the ACL deletion to work (along with the acl write policy). Have a few suggestions but this looks excellent!

I havent tested this myself though.

File: connect-inject/endpoints_controller_ent_test.go (hunk 3 above)
Comment (ishustava) [reply connect-inject/endpoints_controller_ent_test.go:1542]: lol so true!

**Comment by ishustava** [comment]
Thank you so much for the review @thisisnotashwin 🙏 🙏 I know it was a bit of a handful to read with all the refactors!

File: connect-inject/endpoints_controller.go [hunk 7]
```diff
@@ -710,19 +716,94 @@ func (r *EndpointsController) deregisterServiceOnAllAgents(ctx context.Context,
 						r.Log.Error(err, "failed to deregister service instance", "id", svcID)
 						return err
 					}
+
+					if r.AuthMethod != "" {
+						r.Log.Info("deleting ACL token for service instance", "id", svcID)
+						// We don't check that these keys exist in the map because we expect that they always do by the time we're
+						// looking at this service registration.
```
Comment (ndhanushkodi) [inline connect-inject/endpoints_controller.go:723]: We definitely expect the MetaKeyKubeNS to exist because we get services using the namespace in line 701, but if MetaKeyPodName is missing (even just due to a user error) do we want this code to panic, or just log the error in deleting the ACL token? 

Maybe since Meta keys are something a user could potentially have automation around, if they wrote something with a bug that removed MetaKeyPodName I'm sure it would cause lots of problems, but maybe just worth thinking if we want a panic in that case or a handled error. I think I'm just leaning slightly towards handled error but if its really not possible to get to this line in that case, its totally fine if you think otherwise!

File: connect-inject/endpoints_controller_test.go [hunk 8]
```diff
@@ -2029,123 +2038,347 @@ func TestReconcileUpdateEndpoint(t *testing.T) {
...
-				caFile, certFile, keyFile := common.GenerateServerCerts(t)
-				// Create test consul server, with ACLs+TLS if necessary
-				consul, err := testutil.NewTestServerConfigT(t, func(c *testutil.TestServerConfig) {
-					if secure {
-						c.ACL.Enabled = true
-						c.ACL.DefaultPolicy = "deny"
-						c.ACL.Tokens.Master = masterToken
-						c.CAFile = caFile
-						c.CertFile = certFile
-						c.KeyFile = keyFile
```
Comment (ndhanushkodi) [inline connect-inject/endpoints_controller_test.go:2064]: Is this removed because it's just a test and what we care about is the ACL behaviour and not whether the traffic is TLS?

**Review by ndhanushkodi — APPROVED** [review]
Wow this touches a lot of places and makes it so nice and clean to read! I especially like that you pulled the K8sAuthMethod functions out into test_util. Awesome work, and I just had a few questions.

File: connect-inject/endpoints_controller.go (hunk 7 above)
Comment (ishustava) [reply connect-inject/endpoints_controller.go:723]: That's a great question!

I've changed `serviceRegistration.Meta[MetaKeyKubeNS]` to `k8sSvcNamespace` which is already passed as an argument to that function. Thank you for pointing that out!

Thinking about the `MetaKeyPodName` behavior, I'm leaning towards keeping it as is because:
1. Golang maps won't panic if the key doesn't exist: https://play.golang.org/p/yJe52t5c0W6 . Instead, they return an empty string.
2. If pod name is an empty string, then the `deleteACLTokenForService` won't be able to find the token for the service because there will be no token with metadata `{"pod": "/<the value of k8sSvcNamespace>"` and will result in a no-op. I think this is the correct behavior since we can't determine the token that needs to be deleted. We also shouldn't error because that will trigger reconciliation again.

One thing that could be useful though is logging that the pod name meta key is missing if it's not found. WDYT?

File: connect-inject/endpoints_controller_test.go (hunk 8 above)
Comment (ishustava) [reply connect-inject/endpoints_controller_test.go:2064]: I'm removing because there isn't any behavior in the endpoints controller that's specific to TLS. Since we're passing the consul client to the endpoints controller struct, so long as that client is configured correctly, everything will work. We're configuring that client in the test as well, and so there's no way this test could ever fail. Since it can't fail, I don't think it's that useful to us.

What triggered it though is that with TLS and ACL table tests, adding new tests was getting a hard. At first, I was thinking of separating those tests and refactoring to make them a bit more readable with the new ACL tests added. But then realized that they can't fail, and so we should probably just remove them.

File: connect-inject/endpoints_controller.go (hunk 7 above)
Comment (ishustava) [reply connect-inject/endpoints_controller.go:723]: Actually, your question made me realize that I wasn't handling a case where you have orphaned tokens, i.e. tokens for which there are no service registrations. As a result of fixing that, I no longer need to access pod name from the registration and instead check whether the pod exists in kubernetes. That seems like a better solution to me and it also made the code a bit easier!

Thank you so much for asking such great questions ❤️
